"""add_admin_and_office_fields

Revision ID: 02375f05a080
Revises: cdbc322f0cd3
Create Date: 2026-04-30 19:32:28.370398

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02375f05a080'
down_revision: Union[str, Sequence[str], None] = 'cdbc322f0cd3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admins', sa.Column('office_id', sa.Uuid(), nullable=True))
    op.add_column('admins', sa.Column('username', sa.String(length=50), nullable=True))
    op.add_column('admins', sa.Column('role', sa.String(length=50), nullable=False))
    op.create_unique_constraint(None, 'admins', ['username'])
    op.create_foreign_key(None, 'admins', 'allied_offices', ['office_id'], ['id'])
    op.add_column('volunteers', sa.Column('office_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'volunteers', 'allied_offices', ['office_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'volunteers', type_='foreignkey')
    op.drop_column('volunteers', 'office_id')
    op.drop_constraint(None, 'admins', type_='foreignkey')
    op.drop_constraint(None, 'admins', type_='unique')
    op.drop_column('admins', 'role')
    op.drop_column('admins', 'username')
    op.drop_column('admins', 'office_id')
    # ### end Alembic commands ###
