"""change to titles

Revision ID: 0e92abf811f2
Revises: cb42cea19204
Create Date: 2026-04-17 13:14:59.346882

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e92abf811f2'
down_revision: Union[str, Sequence[str], None] = 'cb42cea19204'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('programs', sa.Column('titles', sa.String(length=100), nullable=False))
    op.drop_column('programs', 'title')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('programs', sa.Column('title', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_column('programs', 'titles')
    # ### end Alembic commands ###
