"""add motivation attr to vols application

Revision ID: 1d2dcd734f63
Revises: f7a9c196a14e
Create Date: 2026-04-25 12:15:47.525801

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d2dcd734f63'
down_revision: Union[str, Sequence[str], None] = 'f7a9c196a14e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('volunteer_applications', sa.Column('motivation', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('volunteer_applications', 'motivation')
    # ### end Alembic commands ###
