"""add handler to volunteer create application

Revision ID: 23d502956066
Revises: 7fcdebd8a91b
Create Date: 2026-05-05 22:36:04.166491

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23d502956066'
down_revision: Union[str, Sequence[str], None] = '7fcdebd8a91b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('volunteer_applications', sa.Column('external_handle', sa.String(length=100), nullable=True))
    op.execute("UPDATE volunteer_applications SET external_handle = '' WHERE external_handle IS NULL")
    op.alter_column('volunteer_applications', 'external_handle', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('volunteer_applications', 'external_handle')
    # ### end Alembic commands ###
