"""add public_case_id

Revision ID: 4253644793f2
Revises: 3b12e69adb79
Create Date: 2026-04-29 23:59:59.138863

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4253644793f2'
down_revision: Union[str, Sequence[str], None] = '3b12e69adb79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Add new columns
    op.add_column('incident_tickets', sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False))
    op.add_column('incident_tickets', sa.Column('public_case_id', sa.String(length=20), nullable=False))
    op.create_index(op.f('ix_incident_tickets_public_case_id'), 'incident_tickets', ['public_case_id'], unique=True)
    
    # Drop constraints depending on case_id
    op.drop_constraint('notifications_ticket_id_fkey', 'notifications', type_='foreignkey')
    op.drop_constraint('ticket_status_logs_ticket_id_fkey', 'ticket_status_logs', type_='foreignkey')
    
    # Drop old primary key constraint
    op.drop_constraint('incident_tickets_pkey', 'incident_tickets', type_='primary')
    
    # Now we can drop case_id
    op.drop_column('incident_tickets', 'case_id')
    
    # Create new primary key constraint on id
    op.create_primary_key('incident_tickets_pkey', 'incident_tickets', ['id'])
    
    # Recreate foreign keys
    op.create_foreign_key('notifications_ticket_id_fkey', 'notifications', 'incident_tickets', ['ticket_id'], ['id'])
    op.create_foreign_key('ticket_status_logs_ticket_id_fkey', 'ticket_status_logs', 'incident_tickets', ['ticket_id'], ['id'])


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ticket_status_logs', type_='foreignkey')
    op.create_foreign_key(op.f('ticket_status_logs_ticket_id_fkey'), 'ticket_status_logs', 'incident_tickets', ['ticket_id'], ['case_id'])
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.create_foreign_key(op.f('notifications_ticket_id_fkey'), 'notifications', 'incident_tickets', ['ticket_id'], ['case_id'])
    op.add_column('incident_tickets', sa.Column('case_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_incident_tickets_public_case_id'), table_name='incident_tickets')
    op.drop_column('incident_tickets', 'public_case_id')
    op.drop_column('incident_tickets', 'id')
    # ### end Alembic commands ###
