"""add profile_image_key to volunteers

Revision ID: 7fcdebd8a91b
Revises: 02375f05a080
Create Date: 2026-05-02 00:37:10.371776

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7fcdebd8a91b'
down_revision: Union[str, Sequence[str], None] = '02375f05a080'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('volunteers', sa.Column('profile_image_key', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('volunteers', 'profile_image_key')
    # ### end Alembic commands ###
