"""change to title again

Revision ID: accc1c715f5b
Revises: 0e92abf811f2
Create Date: 2026-04-17 13:16:06.488379

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'accc1c715f5b'
down_revision: Union[str, Sequence[str], None] = '0e92abf811f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('programs', sa.Column('title', sa.String(length=100), nullable=False))
    op.drop_column('programs', 'titles')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('programs', sa.Column('titles', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_column('programs', 'title')
    # ### end Alembic commands ###
