"""add fields to notifications

Revision ID: cdbc322f0cd3
Revises: 4253644793f2
Create Date: 2026-04-30 00:03:35.064419

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cdbc322f0cd3'
down_revision: Union[str, Sequence[str], None] = '4253644793f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('recipient_id', sa.String(length=100), nullable=False))
    op.add_column('notifications', sa.Column('message', sa.String(length=255), nullable=False))
    op.add_column('notifications', sa.Column('status', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notifications', 'status')
    op.drop_column('notifications', 'message')
    op.drop_column('notifications', 'recipient_id')
    # ### end Alembic commands ###
