"""add missing tables/entities again

Revision ID: f7a9c196a14e
Revises: 60a2512b36a5
Create Date: 2026-04-20 19:46:04.488548

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7a9c196a14e'
down_revision: Union[str, Sequence[str], None] = '60a2512b36a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('allied_offices',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('acronym', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contact_lines',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('office_id', sa.Uuid(), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('channel_type', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['office_id'], ['allied_offices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('incident_tickets',
    sa.Column('case_id', sa.String(length=16), nullable=False),
    sa.Column('demographic', sa.String(length=50), nullable=False),
    sa.Column('locality', sa.String(length=50), nullable=False),
    sa.Column('involved_party', sa.String(length=50), nullable=False),
    sa.Column('routing_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('assigned_volunteer_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assigned_volunteer_id'], ['volunteers.id'], ),
    sa.PrimaryKeyConstraint('case_id')
    )
    op.create_table('notifications',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('ticket_id', sa.String(length=16), nullable=False),
    sa.Column('recipient_type', sa.String(length=100), nullable=False),
    sa.Column('channel', sa.String(length=100), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ticket_id'], ['incident_tickets.case_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ticket_status_logs',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('ticket_id', sa.String(length=16), nullable=False),
    sa.Column('volunteer_id', sa.Uuid(), nullable=True),
    sa.Column('from_status', sa.String(length=100), nullable=False),
    sa.Column('to_status', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['ticket_id'], ['incident_tickets.case_id'], ),
    sa.ForeignKeyConstraint(['volunteer_id'], ['volunteers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ticket_status_logs')
    op.drop_table('notifications')
    op.drop_table('incident_tickets')
    op.drop_table('contact_lines')
    op.drop_table('allied_offices')
    # ### end Alembic commands ###
