import uuid
from sqlalchemy import String, text
from sqlalchemy.orm import Mapped, mapped_column
from .base import Base


class ProgramEntity(Base):
    __tablename__ = "programs"

    # Primary Key using UUID v4 generated by the database
    id: Mapped[uuid.UUID] = mapped_column(
        primary_key=True, server_default=text("gen_random_uuid()")
    )

    # Program Title (e.g., "Safe Spaces Workshop", "Volunteer Training")
    title: Mapped[str] = mapped_column(String(100), nullable=False)

    # Detailed description of the program/initiative
    description: Mapped[str] = mapped_column(String(1000), nullable=False)

    # Status: e.g., 'ongoing', 'planned', 'archived'
    # This helps filter what shows up on the "Showcase Hub"
    status: Mapped[str] = mapped_column(String(20), default="planned", nullable=False)
