from sqlalchemy import String, ForeignKey, text
from sqlalchemy.orm import Mapped, mapped_column, relationship
from .base import Base
import uuid


class VolunteerApplicationEntity(Base):
    __tablename__ = "volunteer_applications"
    # Primary Key using UUID v4 generated by the database
    application_id: Mapped[uuid.UUID] = mapped_column(
        primary_key=True, server_default=text("gen_random_uuid()")
    )
    # Applicant Information
    first_name: Mapped[str] = mapped_column(String(100), nullable=False)
    last_name: Mapped[str] = mapped_column(String(100), nullable=False)
    motivation: Mapped[str] = mapped_column(String(100), nullable=False)
    public_alias: Mapped[str] = mapped_column(String(50), nullable=False)
    email: Mapped[str] = mapped_column(String(100), nullable=False)
    # Application State: e.g., 'pending', 'approved', 'rejected'
    status: Mapped[str] = mapped_column(String(20), default="pending", nullable=False)
    # # Foreign Key: References the admin who reviewed the application
    reviewed_by: Mapped[uuid.UUID | None] = mapped_column(
        ForeignKey("admins.id"), nullable=True
    )
    reviewer = relationship("AdminEntity", back_populates="reviewed_applications")
