from sqlalchemy import String, ForeignKey, text
from sqlalchemy.orm import Mapped, mapped_column, relationship
from .base import Base
import uuid


class VolunteerApplicationEntity(Base):
    __tablename__ = "volunteer_applications"

    # Primary Key using UUID v4 generated by the database
    application_id: Mapped[uuid.UUID] = mapped_column(
        primary_key=True, server_default=text("gen_random_uuid()")
    )

    # Applicant Information
    full_name: Mapped[str] = mapped_column(String(100), nullable=False)

    # This will be migrated to the Volunteers table upon approval
    public_alias: Mapped[str] = mapped_column(String(50), nullable=False)

    # Contact info for the recruitment process
    email: Mapped[str] = mapped_column(String(100), nullable=False)

    # Application State: e.g., 'pending', 'approved', 'rejected'
    status: Mapped[str] = mapped_column(String(20), default="pending", nullable=False)

    # # Foreign Key: References the admin who reviewed the application
    # reviewed_by: Mapped[uuid.UUID | None] = mapped_column(
    #     ForeignKey("admins.admin_id"), nullable=True
    # )
    #
    # # Relationships
    # # Link to the Admin entity for auditing who approved/rejected
    # reviewer = relationship("AdminEntity", back_populates="reviewed_applications")
    #
    # One-to-one logical link: Once approved, this application "becomes" a volunteer
    # Note: In the DB this is often handled by a service logic that creates a
    # record in 'volunteers' using data from this 'application'.
